### ISSUE TITLE
`proto: not found` Error

### ISSUE THREAD

**Issue by shellscape** [moonrepo/setup-moon-action#4]
Since yesterday afternoon, we're now getting `/home/runner/.proto/bin/pnpm: line 7: exec: proto: not found` errors on all of our CI runs that use this action.

Here's our setup config:

 ```yml
       - name: Setup Moon
        uses: moonrepo/setup-moon-action@v1
        with:
          version: 1.14.1
```

Stepping back to `uses: moonrepo/setup-moon-action@v1.2.0` resolved the issue for what it's worth.
